name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: lnguyennb
      IMAGE: cicd-lab-frontend
      PLATFORMS: "linux/amd64,linux/arm64"

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_CREDENTIALS }}
    - 
      name: Build and push tag ${{ github.sha }}
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
    - 
      name: Build and push tag latest
      uses: docker/build-push-action@v5
      with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
