name: Docker Image Build Test

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:

    runs-on: ubuntu-latest

    env:
      REGISTRY: lnguyennb
      IMAGE: cicd-lab-frontend
      PLATFORMS: "linux/amd64,linux/arm64"

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Build and push tag ${{ github.sha }}
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ env.PLATFORMS }}
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}


